version: '3.8'
services:

  database:
    image: postgres
    container_name: clothed-postgres
    env_file:
      - ./api/.env
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - "./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
      - "./db/init_user.sql:/docker-entrypoint-initdb.d/init_user.sql"
    networks:
      - clothed-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d clothed_db"]
      interval: 1s
      timeout: 5s
      retries: 5

  adminer:
    container_name: clothed-amirer
    image: adminer
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - clothed-network
    

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: clothed-client
    image: clothed-client-img
    ports:
      - 5173:5173
    networks:
      - clothed-network
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: clothed-api
    image: clothed-api-img
    restart: on-failure
    env_file:
      - ./api/.env
    ports:
      - 5555:5555
    depends_on:
      database:
        condition: service_healthy
    networks:
      - clothed-network
    volumes:
      - /app/node_modules
      - ./api:/app

networks:
  clothed-network: